name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-browser
        pip install -r requirements.txt || echo "No requirements.txt found"
        
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # 4. Run Robot Framework tests in order
    - name: Run Robot Framework tests in order
      run: |
        robot -d results \
        ./tests/ci_cd.robot \
        ./tests/Registration_tests.robot \
        ./tests/login_tests.robot \
        ./tests/account_overview_tests.robot \
        ./tests/open_account_tests.robot \
        ./tests/transfer_funds_tests.robot

    # 5. Upload results as artifact
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: results
